<?php

/**
 ***** Notification class(on /data_types/notification) test class.
 *
 *
 * Provide unit tests for the Notification class methods.
 * To access the report generated by these tests, type on the URL: '../notification_test'
 */

require_once("TestCase.php");

require_once(APPPATH."/data_types/User.php");
require_once(APPPATH."/data_types/notification/Notification.php");
require_once(APPPATH."/data_types/notification/BarNotification.php");
require_once(APPPATH."/data_types/notification/RegularNotification.php");
require_once(APPPATH."/data_types/notification/ActionNotification.php");
require_once(APPPATH."/exception/NotificationException.php");

class BarNotification_Test extends TestCase{

    public function __construct(){
        parent::__construct($this);
    }

    public function createTestUser(){
        
        $user = new User(1, "John Doe", FALSE, "johndoe@mail.com");

        return $user;
    }

/* id tests */
    public function shouldInstantiateWithValidId1(){

        $user = $this->createTestUser();
        $content = "Hi John Doe!";
        $id = "1";
        $seen = FALSE;


        $notes = "";
        try{
            $notification = new RegularNotification($user, $content, $id, $seen);
        }catch (SelectionProcessException $e){
            $notification = FALSE;
            $notes = "<b>Thrown Exception:</b> <i>".get_class($e)."</i> - ".$e->getMessage();
        }

        $test_name = "Test if instantiate with the id equals to ".$id;

        $this->unit->run($id, $notification->id(), $test_name, $notes);
    }
    
}