<?php

/**
 * Course controller test class.
 * Provide unit tests for the Course controller methods.
 * Tests based on the test database. Change it on 'config/database.php' to test.
 * Remember to call your test methods in the index method to run them in the test report
 * To access the report generated by these tests, type on the URL: '../course_test'
 */

require_once(APPPATH.'/controllers/course.php');

class Course_Test extends CI_Controller{

	public function __construct(){
		parent::__construct();
		$this->load->library('unit_test');
		$this->unit->use_strict(TRUE);
	}

	public function listAllCoursesShouldReturnAnArray(){
		$course_controller = new Course();

		$result = $course_controller->listAllCourses();

		$this->unit->run($result, 'is_array', "Test if listAllCourses() return an array");
	}

	public function listAllCoursesFirstRowIdShouldBeEqualsToTwo(){
		$course_controller = new Course();

		$result = $course_controller->listAllCourses();

		$expected = "2";

		$test_name = "Test the course id from the first row returned from test database";
		
		$this->unit->run($result[0]['id_course'], $expected, $test_name);
	}

	public function listAllCoursesFirstRowCourseTypeIdShouldBeEqualsToOne(){
		$course_controller = new Course();

		$result = $course_controller->listAllCourses();

		$expected = "1";

		$test_name = "Test the course type id from the first row returned from test database";
		
		$this->unit->run($result[0]['course_type_id'], $expected, $test_name);
	}

	public function listAllCoursesFirstRowCourseNameShouldBeEqualsToExpected(){
		$course_controller = new Course();

		$result = $course_controller->listAllCourses();

		$expected = "Engenharia de Energia";

		$test_name = "Test course name from the first row returned from test database";
		
		$this->unit->run($result[0]['course_name'], $expected, $test_name);
	}

	public function index(){

		// Call your test functions here
		$this->listAllCoursesShouldReturnAnArray();
		$this->listAllCoursesFirstRowIdShouldBeEqualsToTwo();
		$this->listAllCoursesFirstRowCourseTypeIdShouldBeEqualsToOne();
		$this->listAllCoursesFirstRowCourseNameShouldBeEqualsToExpected();

		$test_report = array('unit_report' => $this->unit->report());

		$this->load->view('course/course_test_report', $test_report);
	}

}