<?php

/**
 ***** EmailNotification class(on /data_types/notification/EmailNotification) test class.
 *
 *
 * Provide unit tests for the EmailNotification class .
 * To access the report generated by these tests, type on the URL: '../email_notification_test'
 */

require_once(MODULESPATH."/test/controllers/TestCase.php");
require_once(MODULESPATH."/notification/domain/EmailNotification.php");
require_once(MODULESPATH."/auth/domain/User.php");
require_once(MODULESPATH."/notification/constants/EmailConstants.php");
require_once(MODULESPATH."/notification/exception/EmailNotificationException.php");

class EmailNotification_Test extends TestCase{

    public function __construct(){
        parent::__construct($this);
    }
   
    public function getDefaultUser(){
        $id = 1;
        $userName = "Joao";
        $userEmail = "joao@joao.com";

        $user = new User($id, $userName, FALSE, $userEmail, FALSE, FALSE, FALSE);
        
        return $user;
    }


    public function shouldReturnEmailInformation(){

        $user = $this->getDefaultUser();

        $notes = "";
            $email = new EmailNotification($user);
        try{
            $notes = "Criou";
        }
        catch (EmailNotificationException $e){
            $notes = "<b>Thrown Exception:</b> <i>".get_class($e)."</i> - ".$e->getMessage();
        }

        $test_name = "Test if return the receiver name.";
        $this->unit->run($email->getReceiverName(), $user->getName(), $test_name, $notes);

        $test_name = "Test if return the receiver email.";
        $this->unit->run($email->getReceiverEmail(), $user->getEmail(), $test_name, $notes);
       
        $test_name = "Test if return the sender name.";
        $this->unit->run($email->getSenderName(), EmailConstants::SENDER_NAME, $test_name, $notes);

        $test_name = "Test if return the sender email.";
        $this->unit->run($email->getSenderEmail(), EmailConstants::SENDER_EMAIL, $user->getEmail(), $test_name, $notes);
    }

   
}