<?php

/**
 ***** EnrolledStudentEmail class(on /data_types/notification/emails/EnrolledStudentEmail) test class.
 *
 *
 * Provide unit tests for the EnrolledStudentEmail class .
 * To access the report generated by these tests, type on the URL: '../ enrolled_student_email_test'
 */

require_once(MODULESPATH."/test/controllers/TestCase.php");
require_once(MODULESPATH."notification/domain/emails/EnrolledStudentEmail.php");
require_once(MODULESPATH."notification/exception/EmailNotificationException.php");

class EnrolledStudentEmail_Test extends TestCase{

    public function __construct(){
        parent::__construct($this);
    }
   

    public function getEmailDefaultInformation(){

        $id = 1;
        $userName = "Joao";
        $userEmail = "joao@joao.com";

        $user = new User($id, $userName, FALSE, $userEmail, FALSE, FALSE, FALSE);

        $course =  1;
        $ci =& get_instance();
        $ci->load->model("program/course_model");
        $courseName = $ci->course_model->getCourseName($course);

        $message = "Olá, <b>{$userName}</b>. <br>";
            $message = $message."Estamos te enviando essa mensagem para comunicar que sua matrícula no curso de: <b>".$courseName."</b> foi efetuada.<br>";
            $message = $message."O seu acesso ao SiGA como estudante está liberado."; 

        $emailInfo = array();

        $emailInfo['user'] = $user;
        $emailInfo['course'] = $course;
        $emailInfo['courseName'] = $courseName;
        $emailInfo['subject'] = EnrolledStudentEmail::STUDENT_ENROLLED_SUBJECT;
        $emailInfo['message'] = $message;       

        return $emailInfo;
    }

    public function shouldReturnEmailInformation(){

        $emailInfo = $this->getEmailDefaultInformation();
        $user = $emailInfo['user'];
        $course = $emailInfo['course'];
        $notes = "";
        try{
            $email = new EnrolledStudentEmail($user, $course);
            $notes = "Criou";
        }
        catch (EmailNotificationException $e){
            $notes = "<b>Thrown Exception:</b> <i>".get_class($e)."</i> - ".$e->getMessage();
        }
        
        $test_name = "Test if return the receiver name.";
        $this->unit->run($email->getReceiverName(), $user->getName(), $test_name, $notes);

        $test_name = "Test if return the receiver email.";
        $this->unit->run($email->getReceiverEmail(), $user->getEmail(), $test_name, $notes);
       
        $test_name = "Test if return the sender name.";
        $this->unit->run($email->getSenderName(), EmailConstants::SENDER_NAME, $test_name, $notes);

        $test_name = "Test if return the sender email.";
        $this->unit->run($email->getSenderEmail(), EmailConstants::SENDER_EMAIL, $test_name, $notes);

        $test_name = "Test if return the course.";
        $this->unit->run($email->getCourse(), $emailInfo['courseName'], $test_name, $notes);        

        $test_name = "Test if return the subject.";
        $this->unit->run($email->getSubject(), $emailInfo['subject'], $test_name, $notes);

        $test_name = "Test if return the message.";
        $this->unit->run($email->getMessage(), $emailInfo['message'], $test_name, $notes);
    }

    public function shouldReturnExceptionWithNullCourse(){
        
        $emailInfo = $this->getEmailDefaultInformation();
        $user = $emailInfo['user'];
        $course = NULL;
        $notes = "";
        
        try{
            $email = new EnrolledStudentEmail($user, $course);
            $notes = "Criou";
        }
        catch (EmailNotificationException $e){
            $email = FALSE;
            $notes = "<b>Thrown Exception:</b> <i>".get_class($e)."</i> - ".$e->getMessage();
        }
        
        $test_name = "Test if return the null course.";
        $this->unit->run($email, 'is_false', $test_name, $notes);
    }

}